name: apprail
description: A Railway Cable Route Visualization App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^1.0.3
  carousel_slider: ^4.2.1
  adaptive_theme: ^2.0.0

  # Map core
  flutter_map: ^8.2.1
  flutter_map_cache: ^2.0.0+1
  latlong2: ^0.9.0

  # Show current location
  flutter_map_location_marker: ^10.1.0

  # GPS + Geocoding
  geolocator: ^14.0.0
  geocoding: ^4.0.0
  # Permission handling
  permission_handler: ^11.3.1
  # Supabase authentication
  supabase_flutter: ^2.8.1
  # Search & API calls
  dio: ^5.4.0
  # Path provider for cache storage
  path_provider: ^2.1.4

  # UI
  cupertino_icons: ^1.0.8
  fluttertoast: ^8.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lucknow_network.geojson

